# Request
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "loginId": "testId10",
  "password": "1234",
  "name": "test-name",
  "email": "test@test.com"
}

###
# Request
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "loginId": "testId10",
  "password": "1234"
}

###
# Request
GET http://localhost:8080/users/me
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJEQU9VIiwic3ViIjoie3Byb2plY3RfbmFtZX0iLCJsb2dpbklkIjoidGVzdElkMTAiLCJpYXQiOjE2NjU0Njg0OTUsImV4cCI6MTY2NTQ3MDI5NX0.aqA40I5qxPKwMuf_MRjcqhp0KrmzeTlfsSs0jZm3BzNWfSgw8W9yfpLPX6cGLiBD5jthqo7ToW6V_wD2KLdGZA