# Request
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "loginId": "testId10",
  "password": "1234",
  "name": "test-name",
  "email": "test@test.com"
}

###
# Request
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "loginId": "testId10",
  "password": "1234"
}

###
# Request
GET http://localhost:8080/users/me
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJEQU9VIiwic3ViIjoie3Byb2plY3RfbmFtZX0iLCJsb2dpbklkIjoidGVzdElkMTAiLCJpYXQiOjE2NjQ0MjQzNDEsImV4cCI6MTY2NDQyNjE0MX0.5iz3jwQseJUbqPCTNJIjabDofBzyX30NqJOVzZb3elKwtduan4nvohjg211CVtabqTLABrOmaPjg0jDxqJK8-A
